### ISSUE TITLE
Can't install plugin

### ISSUE THREAD

**Issue by msssequeira** [pixeline/KIT-syntax-mode-for-Coda-2#1]
Hi,

I followed the instructions to install (open kit.mode and restart coda), but can't get it installed. Coda just opens the package, showing the folder "Contents". Am I doing something wrong?

I'm using Coda 2 in Mac Os X 10.9.2.

Any help is appreciated.

**Comment by pixeline** [comment]
Sorry _ never noticed your Issue before. It seems a Coda update broke it. 
I just updated the plugin, it should work now.
